image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
    before: |
      echo "tasks - before"
    command: |
      mkdir -p .secrets
      echo $PLAYGROUND_STAGING_P12 |base64 -d > .secrets/playground.staging.api-creds.p12
      echo $PUBLIC_SERVER_CA |base64 -d | zcat > .secrets/public_server_ca.crt
      export VOLT_API_URL="https://playground.staging.volterra.us/api"
      export VOLT_API_P12_FILE="/workspace/f5-xc-lb-nginx/.secrets/playground.staging.api-creds.p12"
      export VOLT_API_CA_CERT="/workspace/f5-xc-lb-nginx/.secrets/public_server_ca.crt"
      #terraform init
      #terraform apply --auto-approve
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
