image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
    before: |
      echo "tasks - before"
    command: |
      mkdir -p .secrets
      echo $PLAYGROUND_STAGING_P12 |base64 -d > .secrets/playground.staging.api-creds.p12
      echo $PUBLIC_SERVER_CA |base64 -d | zcat > .secrets/public_server_ca.crt
      #
      terragrunt run-all apply --terragrunt-non-interactive
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
