image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      echo "tasks - before"
      echo $PLAYGROUND_STAGING_P12 |base64 -d > ~/playground.staging.api-creds.p12
      echo $PUBLIC_SERVER_CA |base64 -d | zcat > ~/public_server_ca.crt
      gp env VOLT_API_URL="https://playground.staging.volterra.us/api"
      gp env VOLT_API_P12_FILE="/home/gitpod/playground.staging.api-creds.p12"
      gp env VOLT_API_CA_CERT="/home/gitpod/public_server_ca.crt"
      echo "server-urls: $VOLT_API_URL" > ~/.vesconfig
      echo "p12-bundle: $VOLT_API_P12_FILE" >> ~/.vesconfig
  - init: |
      echo "tasks - init"
      terraform init
      terraform apply --auto-approve
      /bin/bash ./build_container.sh
      until kubectl cluster-info; do echo "waiting since $SECONDS ..." && sleep 5; done
      echo "vk8s cluster ready. Deploying staticnginx to all regional edges ..."
      kubectl apply -f webserver.yaml
    command: |
      echo "tasks - command"
      terraform apply --auto-approve
      kubectl get pods -o wide
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
