image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      echo "tasks - init"
      echo $PLAYGROUND_STAGING_P12 |base64 -d > ~/playground.staging.api-creds.p12
      echo $PUBLIC_SERVER_CA |base64 -d | zcat > ~/public_server_ca.crt
      export VOLT_API_URL="https://playground.staging.volterra.us/api"
      export VOLT_API_P12_FILE="/home/gitpod/playground.staging.api-creds.p12"
      export VOLT_API_CA_CERT="/home/gitpod/public_server_ca.crt"
      echo "server-urls: $VOLT_API_URL" > ~/.vesconfig
      echo "p12-bundle: $VOLT_API_P12_FILE" >> ~/.vesconfig
    before: |
      echo "tasks - before"
    command: |
      echo "tasks - command"
      terraform init
      terraform apply --auto-approve
    
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
